### ISSUE TITLE
"31" is hardcoded on line 29. Needs changing to "32"

### ISSUE THREAD

**Issue by handelaar** [tmtmtmtm/ireland-kildarestreet#2]
That's basically it. I'm not forking a new repo for it :)

**Comment by tmtmtmtm** [comment]
Fixed in https://github.com/tmtmtmtm/ireland-kildarestreet/commit/f8f79631b95e1ef53a7d28b8a961c3dec68dbce3

At some point it would be good to switch this over to pulling in the full XML version, similarly to https://github.com/tmtmtmtm/australia-openaustralia/blob/master/scraper.rb (though that can also be cleaned up significantly now with https://github.com/everypolitician/combine_popolo_memberships)
